-- MySQL Script generated by MySQL Workbench
-- Mon May 29 10:16:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `youtube` DEFAULT CHARACTER SET utf8mb4 ;
USE `youtube` ;

-- -----------------------------------------------------
-- Table `youtube`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`playlist` (
  `idPlayList` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `datacreació` DATE NOT NULL,
  `public` TINYINT(4) NULL DEFAULT NULL,
  `private` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`idPlayList`),
  UNIQUE INDEX `idPlayList_UNIQUE` (`idPlayList` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`videopublicat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`videopublicat` (
  `idvideo` INT(11) NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(255) NULL DEFAULT NULL,
  `descripcio` TEXT NOT NULL,
  `grandaria` INT(11) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `durada` INT(11) NOT NULL,
  `thumbnail` VARCHAR(45) NULL DEFAULT NULL,
  `numero de reproduccions` INT(11) NOT NULL,
  `numero de likes` INT(11) NOT NULL,
  `numero de dislikes` INT(11) NOT NULL,
  `playlist_idPlayList` INT(11) NOT NULL,
  PRIMARY KEY (`idvideo`),
  UNIQUE INDEX `idvideo_UNIQUE` (`idvideo` ASC) ,
  INDEX `fk_videopublicat_playlist_idx` (`playlist_idPlayList` ASC) ,
  CONSTRAINT `fk_videopublicat_playlist`
    FOREIGN KEY (`playlist_idPlayList`)
    REFERENCES `youtube`.`playlist` (`idPlayList`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`usuari`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`usuari` (
  `idUsuari` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `data neixament` DATE NULL DEFAULT NULL,
  `sexe` TINYINT(4) NULL DEFAULT NULL COMMENT '0 --> Home\\n1 --> Dona',
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `datapenjatvídeo` DATE NULL DEFAULT NULL,
  `videopublicat_idvideo` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuari`),
  UNIQUE INDEX `idUsuari_UNIQUE` (`idUsuari` ASC) ,
  INDEX `fk_usuari_videopublicat1_idx` (`videopublicat_idvideo` ASC) ,
  CONSTRAINT `fk_usuari_videopublicat1`
    FOREIGN KEY (`videopublicat_idvideo`)
    REFERENCES `youtube`.`videopublicat` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`canal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`canal` (
  `idcanal` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `DATA` DATE NOT NULL,
  `usuari_idUsuari` INT(11) NOT NULL,
  PRIMARY KEY (`idcanal`),
  UNIQUE INDEX `idcanal_UNIQUE` (`idcanal` ASC) ,
  INDEX `fk_canal_usuari1_idx` (`usuari_idUsuari` ASC) ,
  CONSTRAINT `fk_canal_usuari1`
    FOREIGN KEY (`usuari_idUsuari`)
    REFERENCES `youtube`.`usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`comentaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`comentaris` (
  `idcomentaris` INT(11) NOT NULL AUTO_INCREMENT,
  `text` TEXT NOT NULL,
  `data` DATE NOT NULL,
  `videopublicat_idvideo` INT(11) NOT NULL,
  `usuari_idUsuari` INT(11) NOT NULL,
  PRIMARY KEY (`idcomentaris`),
  UNIQUE INDEX `idcomentaris_UNIQUE` (`idcomentaris` ASC) ,
  INDEX `fk_comentaris_videopublicat1_idx` (`videopublicat_idvideo` ASC) ,
  INDEX `fk_comentaris_usuari1_idx` (`usuari_idUsuari` ASC) ,
  CONSTRAINT `fk_comentaris_videopublicat1`
    FOREIGN KEY (`videopublicat_idvideo`)
    REFERENCES `youtube`.`videopublicat` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentaris_usuari1`
    FOREIGN KEY (`usuari_idUsuari`)
    REFERENCES `youtube`.`usuari` (`idUsuari`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`estatdevídeo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`estatdevídeo` (
  `idEstatDeVídeo` INT(11) NOT NULL,
  `OcultPrivatPublic` ENUM('Ocult', 'Privat', 'Públic') NOT NULL,
  `videopublicat_idvideo` INT(11) NOT NULL,
  PRIMARY KEY (`idEstatDeVídeo`),
  UNIQUE INDEX `idEstatDeVídeo_UNIQUE` (`idEstatDeVídeo` ASC) ,
  INDEX `fk_estatdevídeo_videopublicat1_idx` (`videopublicat_idvideo` ASC) ,
  CONSTRAINT `fk_estatdevídeo_videopublicat1`
    FOREIGN KEY (`videopublicat_idvideo`)
    REFERENCES `youtube`.`videopublicat` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`etiquetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`etiquetes` (
  `idetiquetes` INT(11) NOT NULL AUTO_INCREMENT,
  `Usuari_id` INT(11) NOT NULL,
  `data i hora penjat` DATETIME NOT NULL,
  `videopublicat_idvideo` INT(11) NOT NULL,
  PRIMARY KEY (`idetiquetes`),
  UNIQUE INDEX `idetiquetes_UNIQUE` (`idetiquetes` ASC) ,
  INDEX `fk_etiquetes_videopublicat1_idx` (`videopublicat_idvideo` ASC) ,
  CONSTRAINT `fk_etiquetes_videopublicat1`
    FOREIGN KEY (`videopublicat_idvideo`)
    REFERENCES `youtube`.`videopublicat` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`registre likesdislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`registre likesdislikes` (
  `idRegistre likesDislikes` INT(11) NOT NULL AUTO_INCREMENT,
  `Data` DATETIME NULL DEFAULT NULL,
  `LikeOrDislike` ENUM('Like', 'Dislike') NULL DEFAULT NULL,
  `videopublicat_idvideo` INT(11) NOT NULL,
  `comentaris_idcomentaris` INT(11) NOT NULL,
  PRIMARY KEY (`idRegistre likesDislikes`),
  INDEX `fk_registre likesdislikes_videopublicat1_idx` (`videopublicat_idvideo` ASC) ,
  INDEX `fk_registre likesdislikes_comentaris1_idx` (`comentaris_idcomentaris` ASC) ,
  CONSTRAINT `fk_registre likesdislikes_videopublicat1`
    FOREIGN KEY (`videopublicat_idvideo`)
    REFERENCES `youtube`.`videopublicat` (`idvideo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registre likesdislikes_comentaris1`
    FOREIGN KEY (`comentaris_idcomentaris`)
    REFERENCES `youtube`.`comentaris` (`idcomentaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `youtube`.`subscripció`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `youtube`.`subscripció` (
  `idsubscripció` INT(11) NOT NULL AUTO_INCREMENT,
  `canal_idcanal` INT(11) NOT NULL,
  PRIMARY KEY (`idsubscripció`),
  UNIQUE INDEX `idsubscripció_UNIQUE` (`idsubscripció` ASC) ,
  INDEX `fk_subscripció_canal1_idx` (`canal_idcanal` ASC) ,
  CONSTRAINT `fk_subscripció_canal1`
    FOREIGN KEY (`canal_idcanal`)
    REFERENCES `youtube`.`canal` (`idcanal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
