-- MySQL Script generated by MySQL Workbench
-- Wed May 24 13:15:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizzeríadom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizzeríadom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizzeríadom` DEFAULT CHARACTER SET utf8mb4 ;
USE `pizzeríadom` ;

-- -----------------------------------------------------
-- Table `pizzeríadom`.`begudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`begudes` (
  `idbegudes` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idbegudes`),
  UNIQUE INDEX `idbegudes_UNIQUE` (`idbegudes` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`província`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`província` (
  `idprovíncia` INT(11) NOT NULL AUTO_INCREMENT,
  `nom provincia` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idprovíncia`),
  UNIQUE INDEX `idprovíncia_UNIQUE` (`idprovíncia` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`localitat` (
  `idlocalitat` INT(11) NOT NULL AUTO_INCREMENT,
  `nom localitat` VARCHAR(255) NOT NULL,
  `província_idprovíncia` INT(11) NOT NULL,
  PRIMARY KEY (`idlocalitat`),
  UNIQUE INDEX `idlocalitat_UNIQUE` (`idlocalitat` ASC) ,
  INDEX `fk_localitat_província1_idx` (`província_idprovíncia` ASC) ,
  CONSTRAINT `fk_localitat_província1`
    FOREIGN KEY (`província_idprovíncia`)
    REFERENCES `pizzeríadom`.`província` (`idprovíncia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`botiga` (
  `idbotiga` INT(11) NOT NULL AUTO_INCREMENT,
  `adreça` VARCHAR(255) NOT NULL,
  `localitat_id` INT(11) NULL DEFAULT NULL,
  `provincia_id` INT(11) NULL DEFAULT NULL,
  `zip` INT(11) NOT NULL,
  `localitat_idlocalitat` INT(11) NOT NULL,
  PRIMARY KEY (`idbotiga`),
  UNIQUE INDEX `idbotiga_UNIQUE` (`idbotiga` ASC) ,
  INDEX `fk_botiga_localitat1_idx` (`localitat_idlocalitat` ASC) ,
  CONSTRAINT `fk_botiga_localitat1`
    FOREIGN KEY (`localitat_idlocalitat`)
    REFERENCES `pizzeríadom`.`localitat` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`categoría`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`categoría` (
  `idcategoría` INT(11) NOT NULL AUTO_INCREMENT,
  `nom categoría` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoría`),
  UNIQUE INDEX `idcategoría_UNIQUE` (`idcategoría` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`client` (
  `idClient` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  `Teléfon` VARCHAR(45) NOT NULL,
  `Adreça` VARCHAR(45) NULL DEFAULT NULL,
  `Localitat_id` VARCHAR(45) NOT NULL,
  `Provincia_id` VARCHAR(45) NOT NULL,
  `zip` VARCHAR(45) NOT NULL,
  `localitat_idlocalitat` INT(11) NOT NULL,
  PRIMARY KEY (`idClient`),
  UNIQUE INDEX `idClient_UNIQUE` (`idClient` ASC) ,
  INDEX `fk_client_localitat1_idx` (`localitat_idlocalitat` ASC) ,
  CONSTRAINT `fk_client_localitat1`
    FOREIGN KEY (`localitat_idlocalitat`)
    REFERENCES `pizzeríadom`.`localitat` (`idlocalitat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`empleats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`empleats` (
  `idEmpleats` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(255) NOT NULL,
  `telèfon` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `Repartidor` TINYINT(4) NOT NULL,
  `cuiner` TINYINT(4) NOT NULL,
  `botiga_idbotiga` INT(11) NOT NULL,
  PRIMARY KEY (`idEmpleats`),
  UNIQUE INDEX `idEmpleats_UNIQUE` (`idEmpleats` ASC) ,
  UNIQUE INDEX `NIF_UNIQUE` (`NIF` ASC) ,
  INDEX `fk_empleats_botiga_idx` (`botiga_idbotiga` ASC) ,
  CONSTRAINT `fk_empleats_botiga`
    FOREIGN KEY (`botiga_idbotiga`)
    REFERENCES `pizzeríadom`.`botiga` (`idbotiga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`comanda` (
  `idcomanda` INT(11) NOT NULL AUTO_INCREMENT,
  `data` VARCHAR(45) NOT NULL,
  `a domicili` TINYINT(1) NOT NULL COMMENT 'If false --> 0\\nif true --> 1',
  `quantitat` INT(5) NULL DEFAULT NULL,
  `productes_id` INT(11) NOT NULL,
  `empleats_idEmpleats` INT(11) NOT NULL,
  PRIMARY KEY (`idcomanda`),
  UNIQUE INDEX `idcomanda_UNIQUE` (`idcomanda` ASC) ,
  INDEX `fk_comanda_empleats1_idx` (`empleats_idEmpleats` ASC) ,
  CONSTRAINT `fk_comanda_empleats1`
    FOREIGN KEY (`empleats_idEmpleats`)
    REFERENCES `pizzeríadom`.`empleats` (`idEmpleats`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`hamburgueses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`hamburgueses` (
  `idhamburgueses` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(105) NOT NULL,
  PRIMARY KEY (`idhamburgueses`),
  UNIQUE INDEX `idhamburgueses_UNIQUE` (`idhamburgueses` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`pizza` (
  `idpizza` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(255) NOT NULL,
  `categoría_idcategoría` INT(11) NOT NULL,
  PRIMARY KEY (`idpizza`),
  UNIQUE INDEX `idpizza_UNIQUE` (`idpizza` ASC) ,
  INDEX `fk_pizza_categoría1_idx` (`categoría_idcategoría` ASC) ,
  CONSTRAINT `fk_pizza_categoría1`
    FOREIGN KEY (`categoría_idcategoría`)
    REFERENCES `pizzeríadom`.`categoría` (`idcategoría`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizzeríadom`.`productes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizzeríadom`.`productes` (
  `idproductes` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `descripcio` TEXT NOT NULL,
  `imatge` BLOB NULL DEFAULT NULL,
  `preu` FLOAT NOT NULL,
  `comanda_idcomanda` INT(11) NOT NULL,
  `hamburgueses_idhamburgueses` INT(11) NOT NULL,
  `pizza_idpizza` INT(11) NOT NULL,
  `begudes_idbegudes` INT(11) NOT NULL,
  PRIMARY KEY (`idproductes`),
  UNIQUE INDEX `idproductes_UNIQUE` (`idproductes` ASC) ,
  INDEX `fk_productes_comanda1_idx` (`comanda_idcomanda` ASC) ,
  INDEX `fk_productes_hamburgueses1_idx` (`hamburgueses_idhamburgueses` ASC) ,
  INDEX `fk_productes_pizza1_idx` (`pizza_idpizza` ASC) ,
  INDEX `fk_productes_begudes1_idx` (`begudes_idbegudes` ASC) ,
  CONSTRAINT `fk_productes_comanda1`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `pizzeríadom`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productes_hamburgueses1`
    FOREIGN KEY (`hamburgueses_idhamburgueses`)
    REFERENCES `pizzeríadom`.`hamburgueses` (`idhamburgueses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productes_pizza1`
    FOREIGN KEY (`pizza_idpizza`)
    REFERENCES `pizzeríadom`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productes_begudes1`
    FOREIGN KEY (`begudes_idbegudes`)
    REFERENCES `pizzeríadom`.`begudes` (`idbegudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
