-- MySQL Script generated by MySQL Workbench
-- Mon May 29 13:02:57 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify` DEFAULT CHARACTER SET utf8mb4 ;
USE `spotify` ;

-- -----------------------------------------------------
-- Table `spotify`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`artista` (
  `idArtista` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(105) NOT NULL,
  `imatge` LONGBLOB NULL DEFAULT NULL,
  `ArtistaRelacionat` VARCHAR(105) NULL DEFAULT NULL,
  PRIMARY KEY (`idArtista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`album` (
  `idAlbum` INT(11) NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(105) NOT NULL,
  `any` INT(4) NOT NULL,
  `ImatgePortada` LONGBLOB NULL DEFAULT NULL,
  `artista_idArtista` INT(11) NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `fk_album_artista1_idx` (`artista_idArtista` ASC) ,
  CONSTRAINT `fk_album_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `spotify`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`usuaris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`usuaris` (
  `idUsuaris` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(155) NOT NULL,
  `dataNeix` DATE NULL DEFAULT NULL,
  `sexo` TINYINT(4) NULL DEFAULT NULL,
  `país` VARCHAR(150) NULL DEFAULT NULL,
  `zip` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idUsuaris`),
  UNIQUE INDEX `idUsuaris_UNIQUE` (`idUsuaris` ASC) ,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`usuaripremium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`usuaripremium` (
  `idUsuariPremium` INT(11) NOT NULL AUTO_INCREMENT,
  `usuaris_idUsuaris` INT(11) NOT NULL,
  PRIMARY KEY (`idUsuariPremium`),
  INDEX `fk_usuaripremium_usuaris_idx` (`usuaris_idUsuaris` ASC) ,
  CONSTRAINT `fk_usuaripremium_usuaris`
    FOREIGN KEY (`usuaris_idUsuaris`)
    REFERENCES `spotify`.`usuaris` (`idUsuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`playlist` (
  `idPlaylist` INT(11) NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(105) NOT NULL,
  `nombre de cançons` INT(10) NOT NULL,
  `data de creació` DATE NOT NULL,
  `usuaris_idUsuaris` INT(11) NOT NULL,
  `usuaripremium_idUsuariPremium` INT(11) NOT NULL,
  PRIMARY KEY (`idPlaylist`),
  INDEX `fk_playlist_usuaris1_idx` (`usuaris_idUsuaris` ASC) ,
  INDEX `fk_playlist_usuaripremium1_idx` (`usuaripremium_idUsuariPremium` ASC) ,
  CONSTRAINT `fk_playlist_usuaris1`
    FOREIGN KEY (`usuaris_idUsuaris`)
    REFERENCES `spotify`.`usuaris` (`idUsuaris`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_usuaripremium1`
    FOREIGN KEY (`usuaripremium_idUsuariPremium`)
    REFERENCES `spotify`.`usuaripremium` (`idUsuariPremium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`playlistinactiva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`playlistinactiva` (
  `idPlaylistInactiva` INT(11) NOT NULL,
  `Titol` VARCHAR(105) NOT NULL,
  `Nombre de cançons` INT(6) NOT NULL,
  `data eliminació` DATE NOT NULL,
  PRIMARY KEY (`idPlaylistInactiva`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`cançons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`cançons` (
  `idCançons` INT(11) NOT NULL AUTO_INCREMENT,
  `titol` VARCHAR(105) NOT NULL,
  `durada` DECIMAL(10,0) NOT NULL,
  `nombre de reproduccions` INT(10) NULL DEFAULT NULL,
  `playlist_idPlaylist` INT(11) NOT NULL,
  `playlistinactiva_idPlaylistInactiva` INT(11) NOT NULL,
  `album_idAlbum` INT(11) NOT NULL,
  `artista_idArtista` INT(11) NOT NULL,
  PRIMARY KEY (`idCançons`),
  INDEX `fk_cançons_playlist1_idx` (`playlist_idPlaylist` ASC) ,
  INDEX `fk_cançons_playlistinactiva1_idx` (`playlistinactiva_idPlaylistInactiva` ASC) ,
  INDEX `fk_cançons_album1_idx` (`album_idAlbum` ASC) ,
  INDEX `fk_cançons_artista1_idx` (`artista_idArtista` ASC) ,
  CONSTRAINT `fk_cançons_playlist1`
    FOREIGN KEY (`playlist_idPlaylist`)
    REFERENCES `spotify`.`playlist` (`idPlaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cançons_playlistinactiva1`
    FOREIGN KEY (`playlistinactiva_idPlaylistInactiva`)
    REFERENCES `spotify`.`playlistinactiva` (`idPlaylistInactiva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cançons_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `spotify`.`album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cançons_artista1`
    FOREIGN KEY (`artista_idArtista`)
    REFERENCES `spotify`.`artista` (`idArtista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`favoritos` (
  `idFavoritos` INT(11) NOT NULL AUTO_INCREMENT,
  `cançons_idCançons` INT(11) NOT NULL,
  `album_idAlbum` INT(11) NOT NULL,
  PRIMARY KEY (`idFavoritos`),
  INDEX `fk_favoritos_cançons1_idx` (`cançons_idCançons` ASC) ,
  INDEX `fk_favoritos_album1_idx` (`album_idAlbum` ASC) ,
  CONSTRAINT `fk_favoritos_cançons1`
    FOREIGN KEY (`cançons_idCançons`)
    REFERENCES `spotify`.`cançons` (`idCançons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoritos_album1`
    FOREIGN KEY (`album_idAlbum`)
    REFERENCES `spotify`.`album` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`suscripcions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`suscripcions` (
  `idSuscripcions` INT(11) NOT NULL AUTO_INCREMENT,
  `data d´inici` DATE NOT NULL,
  `data renovació` DATE NOT NULL,
  `forma de pagament` ENUM('Pay Pal', 'TCredit') NULL DEFAULT NULL,
  `usuaripremium_idUsuariPremium` INT(11) NOT NULL,
  PRIMARY KEY (`idSuscripcions`),
  INDEX `fk_suscripcions_usuaripremium1_idx` (`usuaripremium_idUsuariPremium` ASC) ,
  CONSTRAINT `fk_suscripcions_usuaripremium1`
    FOREIGN KEY (`usuaripremium_idUsuariPremium`)
    REFERENCES `spotify`.`usuaripremium` (`idUsuariPremium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`registresuscripcions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`registresuscripcions` (
  `idRegistreSuscripcions` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `NumeroDordre` INT(10) UNSIGNED NOT NULL,
  `Total` INT(6) NULL DEFAULT NULL,
  `suscripcions_idSuscripcions` INT(11) NOT NULL,
  PRIMARY KEY (`idRegistreSuscripcions`),
  INDEX `fk_registresuscripcions_suscripcions1_idx` (`suscripcions_idSuscripcions` ASC) ,
  CONSTRAINT `fk_registresuscripcions_suscripcions1`
    FOREIGN KEY (`suscripcions_idSuscripcions`)
    REFERENCES `spotify`.`suscripcions` (`idSuscripcions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`suscripciópaypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`suscripciópaypal` (
  `idsuscripcióPayPal` INT(11) NOT NULL AUTO_INCREMENT,
  `Nom d´usuari` VARCHAR(105) NOT NULL,
  `suscripcions_idSuscripcions` INT(11) NOT NULL,
  PRIMARY KEY (`idsuscripcióPayPal`),
  INDEX `fk_suscripciópaypal_suscripcions1_idx` (`suscripcions_idSuscripcions` ASC) ,
  CONSTRAINT `fk_suscripciópaypal_suscripcions1`
    FOREIGN KEY (`suscripcions_idSuscripcions`)
    REFERENCES `spotify`.`suscripcions` (`idSuscripcions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `spotify`.`suscripciótargetes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify`.`suscripciótargetes` (
  `idtargetes` INT(11) NOT NULL AUTO_INCREMENT,
  `num` INT(11) NOT NULL,
  `mes de caducitat` INT(3) NOT NULL,
  `any de caducitat` INT(4) NOT NULL,
  `codigo seguritat` INT(3) NOT NULL,
  `suscripcions_idSuscripcions` INT(11) NOT NULL,
  PRIMARY KEY (`idtargetes`, `codigo seguritat`),
  UNIQUE INDEX `num_UNIQUE` (`num` ASC) ,
  INDEX `fk_suscripciótargetes_suscripcions1_idx` (`suscripcions_idSuscripcions` ASC) ,
  CONSTRAINT `fk_suscripciótargetes_suscripcions1`
    FOREIGN KEY (`suscripcions_idSuscripcions`)
    REFERENCES `spotify`.`suscripcions` (`idSuscripcions`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
